name: Build, Push Docker Image, and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: itsmanthanbhatt/devops:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
        app-name: 'manthandev1'
        publish-profile: ${{ secrets.FINAL_DEV }}
        images: 'itsmanthanbhatt/devops:latest'
